import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service — MDPilot',
  description: 'Terms governing your use of mdpilot.in and the MDPilot MCP server, operated by Viveon Gizit Pvt Ltd.',
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[var(--md-dark-2)] px-5 sm:px-8 py-16">
      <div className="max-w-2xl mx-auto">

        <div className="mb-10">
          <p className="text-[11px] font-mono font-semibold text-[var(--md-text-tertiary)] uppercase tracking-[0.12em] mb-4">Legal</p>
          <h1 className="text-3xl font-semibold text-[var(--md-text)] tracking-[-0.015em] mb-2">Terms of Service</h1>
          <p className="text-sm text-[var(--md-text-tertiary)]">Last updated: June 8, 2026</p>
        </div>

        <div className="space-y-10 text-[14px] leading-[1.75] text-[var(--md-text-secondary)]">

          <p>
            These terms govern your use of mdpilot.in and the MDPilot MCP server, operated by{' '}
            <strong className="text-[var(--md-text-secondary)]">Viveon Gizit Pvt Ltd</strong>. By using MDPilot, you
            agree to them.
          </p>

          <section>
            <h2 className="text-[15px] font-semibold text-[var(--md-text)] mb-3">The service</h2>
            <p>
              MDPilot generates markdown and AI-context files, converts files to markdown, and exposes
              these as an MCP server for AI coding tools. It is provided as a tool to assist you.
            </p>
          </section>

          <section>
            <div className="p-4 rounded-xl border border-[var(--md-accent)]/[0.18] bg-[var(--md-accent)]/[0.03]">
              <h2 className="text-[15px] font-semibold text-[var(--md-text)] mb-2">AI-generated output — review before relying on it</h2>
              <p>
                MDPilot&apos;s output is generated by AI models and may contain errors, omissions, or
                inaccurate commands, paths, or claims. <strong className="text-[var(--md-text-secondary)]">You are
                responsible for reviewing and testing any output before relying on it</strong>, especially
                configuration, security, or instruction files. We make no guarantee that output is
                accurate, complete, or fit for any purpose.
              </p>
            </div>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-[var(--md-text)] mb-3">Acceptable use</h2>
            <p>You agree not to:</p>
            <ul className="mt-2 space-y-1.5 pl-4">
              {[
                'Use MDPilot for unlawful purposes',
                'Submit other parties\' confidential information or personal data without authority',
                'Attempt to abuse, overload, or reverse-engineer the service',
                'Use it to generate harmful, infringing, or malicious content',
              ].map((item, i) => (
                <li key={i} className="flex items-start gap-2.5">
                  <span className="w-1 h-1 rounded-full bg-[var(--md-text-tertiary)] mt-2.5 shrink-0" />
                  <span>{item}</span>
                </li>
              ))}
            </ul>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-[var(--md-text)] mb-3">Your responsibilities</h2>
            <p>
              When using the MCP server, you supply your own AI provider API key and are responsible
              for your provider costs and for complying with that provider&apos;s terms. Do not submit
              secrets or sensitive credentials. You are responsible for the content you submit.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-[var(--md-text)] mb-3">Intellectual property</h2>
            <p>
              You retain rights to the content you submit and, as between you and us, to the output you
              generate. We retain all rights in the MDPilot platform, software, and brand. (Note: the
              legal status of AI-generated content varies by jurisdiction; you are responsible for how
              you use outputs.)
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-[var(--md-text)] mb-3">Disclaimers</h2>
            <p>
              MDPilot is provided &ldquo;as is&rdquo; and &ldquo;as available,&rdquo; without warranties
              of any kind, express or implied, including merchantability, fitness for a particular
              purpose, and non-infringement, to the maximum extent permitted by law.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-[var(--md-text)] mb-3">Limitation of liability</h2>
            <p>
              To the maximum extent permitted by law, Viveon Gizit Pvt Ltd will not be liable for
              any indirect, incidental, special, consequential, or punitive damages, or for any loss of
              data, profits, or business, arising from your use of MDPilot. Our total liability is
              limited to the amount you paid us, if any, in the 12 months before the claim.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-[var(--md-text)] mb-3">Termination</h2>
            <p>
              We may suspend or discontinue the service, or restrict access for misuse, at any time.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-[var(--md-text)] mb-3">Governing law</h2>
            <p>
              These terms are governed by the laws of India, with exclusive jurisdiction in the courts
              of Bengaluru, Karnataka, India.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-[var(--md-text)] mb-3">Changes</h2>
            <p>
              We may update these terms; continued use after changes means you accept them.
            </p>
          </section>

          <section>
            <h2 className="text-[15px] font-semibold text-[var(--md-text)] mb-3">Contact</h2>
            <p>
              Viveon Gizit Pvt Ltd —{' '}
              <a href="mailto:privacy@mdpilot.in" className="text-[var(--md-accent)]/70 hover:text-[var(--md-accent)] transition-colors">
                privacy@mdpilot.in
              </a>
            </p>
          </section>

        </div>

        <div className="mt-14 pt-8 border-t border-[var(--md-border)] flex items-center gap-6">
          <Link href="/privacy" className="text-[12px] font-mono text-[var(--md-text-tertiary)] hover:text-[var(--md-text-secondary)] transition-colors">← Privacy Policy</Link>
          <Link href="/" className="text-[12px] font-mono text-[var(--md-text-tertiary)] hover:text-[var(--md-text-secondary)] transition-colors">MDPilot →</Link>
        </div>

      </div>
    </div>
  );
}
