import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Files MDPilot generates — reference',
  description:
    'Reference for every markdown file MDPilot generates: AGENTS.md, CLAUDE.md, TASK.md, SPEC.md, README, SKILL.md, DESIGN.md, CONTRIBUTING.md, SECURITY.md, and CONTEXT.md — what each is, who reads it, and where it goes.',
};

const FILES = [
  {
    name: 'README.md',
    badge: 'readme',
    accent: 'var(--md-accent)',
    where: 'Project root',
    readers: 'Everyone',
    desc: 'Your project\'s homepage on GitHub, npm, and PyPI. The first file anyone reads — it determines whether they use your project or move on. MDPilot generates a production-grade README grounded in your actual tech stack, scripts, and project type.',
  },
  {
    name: 'AGENTS.md',
    badge: 'agents',
    accent: 'var(--md-info)',
    where: 'Project root',
    readers: 'GitHub Copilot, Cursor, OpenAI Codex, Claude Code, Windsurf, Zed',
    desc: 'Universal AI coding agent instructions. Tells every AI tool how to work in your project — coding style, available scripts, permission boundaries. Without it, agents guess and often guess wrong. The single most high-leverage file for AI-assisted development.',
  },
  {
    name: 'CLAUDE.md',
    badge: 'claude',
    accent: 'var(--md-accent)',
    where: 'Project root',
    readers: 'Claude Code only',
    desc: 'Claude Code reads this automatically at the start of every session. Contains gotchas and constraints Claude would get wrong from the code alone — project-specific conventions, known footguns, decisions that look wrong but are intentional. Prevents repeated clarification questions.',
  },
  {
    name: 'TASK.md',
    badge: 'task',
    accent: 'var(--md-accent)',
    where: 'Project root, or paste the Agent Prompt block directly',
    readers: 'Claude Code, Cursor, Copilot, Windsurf',
    desc: 'Structured task context generated from a ticket, thread, or description. Contains the goal, acceptance criteria, constraints, and an Agent Prompt block — everything an AI agent needs to start coding with zero clarifying questions. Generated by Task mode.',
  },
  {
    name: 'SPEC.md',
    badge: 'spec',
    accent: 'var(--md-accent)',
    where: 'Project root or attached to the ticket',
    readers: 'Engineering team, project managers',
    desc: 'Engineering specification: user story, functional requirements, technical approach, and testing plan. Use alongside TASK.md for planning, estimation, and review before implementation starts. Generated by Task mode.',
  },
  {
    name: 'SKILL.md',
    badge: 'skill',
    accent: 'var(--md-go)',
    where: 'Project or shared skills directory',
    readers: 'Claude Code, Cursor, Copilot (via agentskills.io standard)',
    desc: 'Defines a reusable capability your AI agent can invoke — like a function the agent can call. The description field is critical: it determines whether the skill gets triggered at the right moment. Generated by Generate mode.',
  },
  {
    name: 'DESIGN.md',
    badge: 'design',
    accent: 'var(--md-accent)',
    where: 'Project root',
    readers: 'Gemini, Claude, Cursor, getdesign.md, Figma plugins',
    desc: 'Nine-section ecosystem spec: Visual Theme, Color Palette, Typography, Component Stylings, Layout, Depth & Elevation, Do\'s and Don\'ts, Responsive Behavior, and Agent Prompt Guide. Follows the getdesign.md / awesome-design-md format so any tool that reads DESIGN.md gets exact tokens — not invented values. Generated by Generate mode.',
  },
  {
    name: 'CONTRIBUTING.md',
    badge: 'contributing',
    accent: 'var(--md-accent)',
    where: 'Project root',
    readers: 'Contributors, GitHub',
    desc: 'GitHub surfaces this to anyone opening an issue or PR. Answers "how do I contribute?" — branch naming, commit conventions, PR process, development setup — so you don\'t have to answer it repeatedly. Generated by Generate mode.',
  },
  {
    name: 'SECURITY.md',
    badge: 'security',
    accent: 'var(--md-caution)',
    where: 'Project root',
    readers: 'Security researchers, GitHub Security tab',
    desc: 'GitHub\'s Security tab links to this. Without it, vulnerability reporters may open public issues exposing the flaw. Covers your supported versions, how to report, and your response timeline. Generated by Generate mode.',
  },
  {
    name: 'CONTEXT.md',
    badge: 'context',
    accent: 'var(--md-info)',
    where: 'Project root, updated each session',
    readers: 'Claude Code, Cursor',
    desc: 'Unlike CLAUDE.md (permanent project context), CONTEXT.md is your daily scratchpad — what you\'re working on today, known broken things, decisions in progress, what to ignore. Update it at the start of each coding session. Generated by Generate mode.',
  },
];

export default function FilesReferencePage() {
  return (
    <div className="max-w-2xl">

      <div className="mb-8">
        <div className="section-label mb-4 w-fit">Concepts</div>
        <h1 className="text-[clamp(1.6rem,4vw,2.4rem)] font-semibold text-[var(--md-text)] tracking-[-0.015em] mb-3 leading-tight">
          Files reference
        </h1>
        <p className="text-[var(--md-text-secondary)] text-[15px] leading-relaxed">
          Every file MDPilot can generate — what it is, who reads it, and where it goes.
        </p>
      </div>

      <div className="space-y-3">
        {FILES.map(file => (
          <div
            key={file.badge}
            className="p-5 rounded-xl border border-[var(--md-border)] bg-[var(--md-surface)]"
          >
            <div className="flex items-start justify-between gap-3 mb-2">
              <code
                className="text-[14px] font-mono font-bold"
                style={{ color: file.accent }}
              >
                {file.name}
              </code>
              <span className="text-[9px] font-mono text-[var(--md-text-tertiary)] shrink-0 mt-1">{file.badge}</span>
            </div>
            <div className="flex flex-col sm:flex-row gap-2 mb-3">
              <div className="flex items-center gap-1.5">
                <span className="text-[10px] font-mono text-[var(--md-text-tertiary)] uppercase tracking-wider">Where</span>
                <span className="text-[11px] text-[var(--md-text-tertiary)]">{file.where}</span>
              </div>
            </div>
            <p className="text-[12px] text-[var(--md-text-tertiary)] leading-relaxed mb-2">{file.desc}</p>
            <div className="flex items-start gap-1.5 mt-2">
              <span className="text-[10px] font-mono text-[var(--md-text-tertiary)] uppercase tracking-wider shrink-0 mt-0.5">Read by</span>
              <span className="text-[11px] text-[var(--md-text-tertiary)] leading-relaxed">{file.readers}</span>
            </div>
          </div>
        ))}
      </div>

      <div className="mt-8 pt-6 border-t border-[var(--md-border)] flex items-center gap-4">
        <Link href="/docs/generate" className="text-[12px] font-mono text-[var(--md-text-tertiary)] hover:text-[var(--md-text-secondary)] transition-colors">
          Generate mode →
        </Link>
        <Link href="/docs/task" className="text-[12px] font-mono text-[var(--md-text-tertiary)] hover:text-[var(--md-text-secondary)] transition-colors">
          Task mode →
        </Link>
      </div>

    </div>
  );
}
